if [ -n "$ZSH_VERSION" ]; then
  export BLACK='%{%F{black}%}'
  export BLUE='%{%F{blue}%}'
  export GREEN='%{%F{green}%}'
  export CYAN='%{%F{cyan}%}'
  export RED='%{%F{red}%}'
  export PURPLE='%{%F{magenta}%}'
  export BROWN='%{%F{yellow}%}'
  export LIGHTGRAY='%{%F{white}%}'
  export DARKGRAY='%{%B%F{black}%}'
  export LIGHTBLUE='%{%B%F{blue}%}'
  export LIGHTGREEN='%{%B%F{green}%}'
  export LIGHTCYAN='%{%B%F{cyan}%}'
  export LIGHTRED='%{%B%F{red}%}'
  export LIGHTPURPLE='%{%B%F{magenta}%}'
  export YELLOW='%{%B%F{yellow}%}'
  export WHITE='%{%B%F{white}%}'
  export NC='%{%b%f%}'
else
  export BLACK='\[\e[0;30m\]'
  export BLUE='\[\e[0;34m\]'
  export GREEN='\[\e[0;32m\]'
  export CYAN='\[\e[0;36m\]'
  export RED='\[\e[0;31m\]'
  export PURPLE='\[\e[0;35m\]'
  export BROWN='\[\e[0;33m\]'
  export LIGHTGRAY='\[\e[0;37m\]'
  export DARKGRAY='\[\e[1;30m\]'
  export LIGHTBLUE='\[\e[1;34m\]'
  export LIGHTGREEN='\[\e[1;32m\]'
  export LIGHTCYAN='\[\e[1;36m\]'
  export LIGHTRED='\[\e[1;31m\]'
  export LIGHTPURPLE='\[\e[1;35m\]'
  export YELLOW='\[\e[1;33m\]'
  export WHITE='\[\e[1;37m\]'
  export NC='\[\e[0m\]'
fi
